name: 'DoDGame Build Environment'
description: 'CI Tools for the DoDGame'
# inputs:
#   java-version:
runs:
    using: 'composite'
    steps:
      - name: Git checkout
        uses: actions/checkout@v3.1.0
        with:
          fetch-depth: '0'
