name: 'DoDGame Build Environment'
description: 'CI Tools for the DoDGame'
inputs:
  java-version:
    description: 'Set Java version to use'
    required: true
    default: '17'
runs:
    using: 'composite'
    steps:
      - name: Git checkout
        uses: actions/checkout@v3.1.0
        with:
          fetch-depth: '0'
      - name: Set up JDK
        uses: actions/setup-java@v3.6.0
        with:
          java-version: ${{ inputs.java-version }}
          distribution: 'adopt'
          cache: gradle
