name: 'Build Environment'
description: 'CI Tools for github actions'
inputs:
  use-java:
    description: 'Whether the step needs Java configured'
    required: true
    default: true
    type: boolean
  java-version:
    description: 'Set Java version to use'
    required: true
    default: '21'
  use-docker:
    description: 'Do you want to use Docker'
    required: true
    default: true
    type: boolean
runs:
  using: 'composite'
  steps:
    - name: Git checkout
      uses: actions/checkout@v4.2.2
      with:
        fetch-depth: '0'
      run:
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
    - name: Set up JDK
      if: ${{ inputs.use-java == 'true' }}
      uses: actions/setup-java@v4.7.1
      with:
        java-version: ${{ inputs.java-version }}
        distribution: 'temurin'
        cache: gradle
    - name: Login to Docker Hub
      if: ${{  inputs.use-docker == 'true' }}
      uses: docker/login-action@v3.4.0
      with:
        username: ${{ env.DOCKER_USER }}
        password: ${{ env.DOCKER_PASSWORD }}

