name: build
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
jobs:
  release:
      runs-on: ubuntu-latest
      steps:
        - name: Merge back to develop
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          git tag -d v0
          git tag v0