name: build
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  workflow_dispatch:      
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
env:
  GITHUB_TOKEN: ${{ secrets.SEMREL_TOKEN }}
  DOCKER_USER: ${{ secrets.DOCKERHUB_USER }}
  DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: '0'
      - uses: mpeki/build-env/pre-build@v1.0.4
      - name: print java version
        run: java -version
      - name: print gradle version
        run: gradle --version
  release:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: Git checkout
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: '0'
      - name: Prepare semantic-release
        run: |
          npm clean-install
      - name: Do semantic-release
        run: npx semantic-release